- name: Installing the required packages
  gather_facts: false
  hosts: cluster
  become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
    - name: Install the required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - docker.io
          - python3-pip
          - python3-dev
          - python3-setuptools
          - containerd
          - docker-compose
          - curl
    # - name: Fetch the repository from github
    #   git:
    #     repo: 
    #     dest: /home/ubuntu/cluster
    #     version: master
    #     clone: yes
    #     force: yes
